<?php
    if(!isset($_SESSION)){
        session_start();
    }
    require_once __DIR__ .'/config.php';
    $thisPage = "BLOG";
?>
<!DOCTYPE html>
<html lang="en">
	<head>
        <?php require_once __DIR__ .'/templates/head.html.php'; ?>
        <link rel="canonical" href="https://www.developerspot.co.ke/blog.php">
        <title>A blogging site dedicated to building websites and web apps</title>
	    <meta name="description" content="Articles dedicated to building websites and web apps that are SEO friendly. The tutorials focuses on both server-side and front end solutions. ">
        <meta name="keywords" content="websites, app, blog, server-side, front end, php, html, javascript, css, solutions"/>
        <!-- Twitter & OG metas -->
        <meta name="twitter:card" content="summary_large_image">
        <meta name="twitter:site" content="@developerspotke">
        <meta name="twitter:creator" content="@fkahindi">
        <meta property="og:url" content="<?php echo $url;?>" />
        <meta property="og:type" content="article" />
        <meta property="og:title" content="A blogging site dedicated to building websites and web apps" />
        <meta property="og:description" content="Articles dedicated to building websites and web apps that are SEO friendly. The tutorials focuses on both server-side and front end solutions." />
        <meta property="og:image" content="<?php echo BASE_URL ?>resources/images/html-doc-structure.png" />
        <meta property="fb:app_id" content="502152493814762"/>

        <?php include_once __DIR__ .'/templates/head-resources.html.php'; ?>
        <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
        <script type="application/ld+json">
            {
            "@context": "http://schema.org/",
            "@type": "WebSite",
            "url": "https://www.developerspot.co.ke/blog",
            "potentialAction": {
                "@type": "SearchAction",
                "target": "{search_term_string}",
                "query-input": "required name=search_term_string"
            }
            }
        </script>
            <!-- Facebook Pixel Code -->
            <script src="resources/js/facebook-pixel.js"></script>
	</head>
	<body>
        <noscript><img height="1" width="1"  class="hidden"
        src="https://www.facebook.com/tr?id=1970631019919003&ev=PageView&noscript=1"
        /></noscript>
        <!-- End Facebook Pixel Code -->
		<header class="grid-wrapper">
            <?php require_once __DIR__ . '/templates/header.html.php';?>
            <?php include __DIR__ .'/templates/social-icons-links.php';?>
            <?php include __DIR__ .'/search/search-form.php';?>
		</header>
		<main class="group">
			<section class="posts-section border-not-last-child-div">
                <h1>Browse Articles </h1>
                <div class="intro-paragraph">
                    <p>
                        Building fast, secure, SEO-friendly web apps is no longer an option, but a requirement in today's tech world. The articles here, is an opportunity to share design ideas that you can use to incorporate into your web development projects. If it helped you, leave a feedback.
                        Happy coding!
                    </p>
                </div>
                <div id="posts_thumbnails">

                    <?php include __DIR__.'/includes/posts-pagination.php'?>
                </div>
                <div id="pagination" class="pagination">
                    <?php if($total_pages>1): ?>
                    <ul id="total_pages" data-id="<?php echo $total_pages;?>">
                        <li class="previous"></li>
                        <?php for($i=1; $i<= $total_pages; $i++){
                        echo '<li class="page-num" data-id="'.$i.'">'.$i.'</li>';}
                        if($total_pages>1){ echo '<li class="next">Next</li>';}
                        ?>
                    </ul>
                    <div class="load-more" data-id="1">
                        <span>Load more...</span>
                        <i class="fa fa-chevron-down"></i>
                    </div>
                    <?php endif ?>
                </div>
			</section>
		</main>
        <script src="<?php echo BASE_URL ?>resources/js/jquery-3.4.0.min.js"></script>
        <script src="<?php echo BASE_URL ?>resources/js/page-control.js"></script>
        <!-- <script src="<?php //echo BASE_URL ?>resources/js/getPostThumbnails.js"></script> -->
        <footer class="grid-wrapper">
        <?php include __DIR__ .'/templates/social-icons-links.php';?>
        <?php include __DIR__ .'/templates/footer.html.php'?>
      </footer>
      <script src="resources/js/blog-pagination.js"></script>
	</body>
</html>