<?php
if(!isset($_SESSION)){
	session_start();
}
	include __DIR__ .'/../admin/includes/posts_functions.php';
	include __DIR__ .'/../admin/includes/admin_functions.php';
	if(isset($_GET['id'])){
		$posts = getPostById($_GET['id']);
		if(empty($posts)){
			header("Location:../index.php");
		}
	}else{
		header("Location:../index.php");
	}
	/* Get page id for this post */ 
	$page_id = $posts['post_id'];
	/* SESSION variables for page reference */ 
	$post_slug = $posts['post_slug'];
	$_SESSION['page_id'] = $page_id;
	$_SESSION['post_slug'] = $post_slug;
	$published_post_ids = getAllPublishedPostIds();
	//modify url dynamically
	
?>
<!DOCTYPE html>
<html lang="en">
<head>
<!-- head section -->
<title><?php echo htmlspecialchars_decode($posts['post_title']) ;?> | DevelopersPot</title>
	<meta name="description" content="<?php echo (isset($posts['meta_description'])? htmlspecialchars_decode($posts['meta_description']):''); ?>" />
	<?php include_once __DIR__ .'/head.html.php';?>
<style>
html,body, div, span, applet, object, iframe, h1, h2, h3, h4, h5, h6, p, blockquote, pre, a, abbr, acronym, address, big, cite, code, del, dfn, em, img, ins, kbd, q, s, samp, small, strike, strong, sub, sup, tt, var, b, u, i, center, dl, dt, dd, ol, ul, li, fieldset, form, label, legend, table, caption, tbody, tfoot, thead, tr, th, td, article, aside, canvas, details, embed, figure, figcaption, footer, header, hgroup, menu, nav, output, ruby, section, summary, time, mark, audio, video {
margin: 0;
padding: 0;
border: 0;
font-size: 100%;
font: inherit;
vertical-align: baseline;
}
article, aside, details, figcaption, figure,
footer, header, hgroup, menu, nav, section {
  display: block;
}

</style>
    <?php include_once __DIR__ .'/head-resources.html.php'; ?>
	<!-- Links for google code prettify .js at bottom of page files -->
	<link rel="stylesheet" href="<?php echo BASE_URL ?>resources/css/google-code-prettify/prettify.css" media="print" onload="this.media='all'; this.onload=null;"/>
    
	<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "Article",
  "name" : "<?php echo ucwords(htmlspecialchars_decode($posts['post_title'])) ?>",
  "headline": "<?php echo ucwords(htmlspecialchars_decode($posts['post_title'])) ?>",
  "datePublished" : "<?php echo date( 'F j, Y', strtotime($posts['created_at'])) ?>",
  "dateModified": "<?php date( 'F j, Y', strtotime($posts['updated_at'])) ?>",
  "image" : "",
  "articleSection" : "<?php echo htmlspecialchars_decode(getFirstParagraphPostById($posts['post_id'])) ?>",
  "author": {
        "@type": "Person",
        "name": "<?php echo $post['author'] = getPostAuthorById($posts['user_id'])?>"
      },
  "publisher" : {
    "@type" : "Organization",
    "name" : "DevelopersPot"
  }
}
</script>
</head>
<body>
	<header>
		<?php include __DIR__ .'/header.html.php';?>
	</header>
	<main class="group">
		<aside class="col-2-10 hide-in-mobile">
				<div>
				<h2>Topics</h2>
				<?php include __DIR__ . '/published_posts_by_topics.html.php';?>
				</div>
		</aside><!--
		--><section class='col-5-10'>
			<!-- The title will be fetched from database -->
			<h1><?php echo ucwords(htmlspecialchars_decode($posts['post_title'])) ;?></h1>
			<div class="post-acreditation">  
				<?php echo isset($posts['updated_at'])? 'Updated on '. date( 'F j, Y', strtotime($posts['updated_at'])): 'Published on '. date( 'F j, Y', strtotime($posts['created_at'])) ?>
			</div>
			<!-- Social icons -->
				<div class="social-media">
					<?php include __DIR__ .'/social-icons-links.php';?>
				</div>
			<div>
                <div class="main-article">
                <!-- The page content will be fetched from database -->
                <?php echo htmlspecialchars_decode($posts['post_body']) ;?>
                </div>
				<div class="social-media">
                <!-- Social icons -->
					<?php include __DIR__ .'/social-icons-links.php';?>
				</div>
				<div>
				<!-- Call to subscribe for notification -->
				<?php  include __DIR__.'/subscribe.html.php';?>
				</div>
				<div>
			<!--Comments sections  -->
			<?php include __DIR__ .'/../comments/comments-layout.php'; ?>
				</div>
			</div>
		</section><!--
		--><aside class='col-3-10'>
			<div class="recent-posts">
			<!-- Sidebar items go here -->
				<h2 class="left">Recent posts</h2>
				<?php include __DIR__ .'/recent_published_posts.html.php'?>
                <div class="contact-me">
                    <?php include __DIR__ . '/contact-me.html.php'?>
                </div>
			</div>
		</aside><!--			
		--><aside class="hide-in-bigger-screens">
				<div class="published-topics">
				<h2 class="left">Browse Topics</h2>
				<?php include __DIR__ . '/published_posts_by_topics.html.php';?>
				</div>
		</aside>
	</main>
	<script src="<?php echo BASE_URL ?>resources/js/jquery-3.4.0.min.js"></script>
	<script src="<?php echo BASE_URL ?>resources/css/google-code-prettify/prettify.js"></script>
	<script src="<?php echo BASE_URL ?>resources/js/page-control.js"></script>
	<script src="<?php echo BASE_URL ?>resources/js/subscribe-comments-replies-scripts.js"></script>	
	<script>window.onload=function(){prettyPrint()}</script>
    <script type="text/javascript"
    src="//assets.pinterest.com/js/pinit.js"
    ></script>
	 <!-- Online server
    
    <script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js?skin=sons-of-obsidian"></script>
    -->
	<footer>
		<?php include __DIR__ .'/footer.html.php'?>
	</footer>
</body>
</html>